# Generated by Django 5.0.4 on 2024-04-06 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_expense_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.FloatField(
                max_length=8,
                validators=[django.core.validators.MaxValueValidator(10000000)],
            ),
        ),
    ]
